#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : links
Version  : 2.17
Release  : 14
URL      : http://links.twibright.com/download/links-2.17.tar.bz2
Source0  : http://links.twibright.com/download/links-2.17.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: links-bin = %{version}-%{release}
Requires: links-license = %{version}-%{release}
Requires: links-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(openssl)
BuildRequires : xz-dev

%description
Links
=====
Contents
--------
1. About
2. Installation
3. Usage
4. Braille terminal support
5. More features

%package bin
Summary: bin components for the links package.
Group: Binaries
Requires: links-license = %{version}-%{release}
Requires: links-man = %{version}-%{release}

%description bin
bin components for the links package.


%package license
Summary: license components for the links package.
Group: Default

%description license
license components for the links package.


%package man
Summary: man components for the links package.
Group: Default

%description man
man components for the links package.


%prep
%setup -q -n links-2.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542692589
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542692589
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/links
cp COPYING %{buildroot}/usr/share/package-licenses/links/COPYING
%make_install
## install_append content
ln -sv links %{buildroot}/usr/bin/elinks
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/elinks
/usr/bin/links

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/links/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/links.1
